from __future__ import annotations

from pathlib import Path

import devtools.demo_env as demo_env


BASE_ENV = """# Generated by quickstart
XRPL_RPC_URL=https://resolved.testnet.rpc/
NETWORK_ID=xrpl:1
XRPL_NETWORK=xrpl:1
MY_DESTINATION_ADDRESS=rMerchant
FACILITATOR_BEARER_TOKEN=top-secret-token
XRPL_WALLET_SEED=sEdSuperSecretSeed
PRICE_DROPS=1000
PRICE_ASSET_CODE=XRP
PRICE_ASSET_ISSUER=
PRICE_ASSET_AMOUNT=
PAYMENT_ASSET=XRP:native
ALLOWED_ISSUED_ASSETS=
"""


def test_demo_env_writes_rlusd_variant_with_extra_allowed_asset(
    monkeypatch,
    tmp_path: Path,
    capsys,
) -> None:
    base_path = tmp_path / ".env.quickstart"
    output_path = tmp_path / ".env.quickstart.rlusd"
    base_path.write_text(BASE_ENV, encoding="utf-8")
    monkeypatch.setattr(demo_env, "default_rlusd_issuer", lambda: "rCustomRLUSDIssuer")

    exit_code = demo_env.main(
        [
            "--asset",
            "rlusd",
            "--base",
            str(base_path),
            "--output",
            str(output_path),
        ]
    )
    captured = capsys.readouterr()

    rendered = output_path.read_text(encoding="utf-8")
    assert exit_code == 0
    assert "PRICE_ASSET_CODE=RLUSD" in rendered
    assert "PRICE_ASSET_ISSUER=rCustomRLUSDIssuer" in rendered
    assert "PRICE_ASSET_AMOUNT=1.25" in rendered
    assert "PAYMENT_ASSET=RLUSD:rCustomRLUSDIssuer" in rendered
    assert "ALLOWED_ISSUED_ASSETS=RLUSD:rCustomRLUSDIssuer" in rendered
    assert "Buyer payment asset: RLUSD:rCustomRLUSDIssuer" in captured.out
    assert "Facilitator extra issued assets: RLUSD:rCustomRLUSDIssuer" in captured.out


def test_demo_env_writes_usdc_variant_without_extra_allowed_asset(
    monkeypatch,
    tmp_path: Path,
) -> None:
    base_path = tmp_path / ".env.quickstart"
    output_path = tmp_path / ".env.quickstart.usdc"
    base_path.write_text(BASE_ENV, encoding="utf-8")
    monkeypatch.setattr(demo_env, "default_usdc_issuer", lambda: "rHuGNhqTG32mfmAvWA8hUyWRLV3tCSwKQt")

    exit_code = demo_env.main(
        [
            "--asset",
            "usdc",
            "--base",
            str(base_path),
            "--output",
            str(output_path),
        ]
    )

    rendered = output_path.read_text(encoding="utf-8")
    assert exit_code == 0
    assert "PRICE_ASSET_CODE=USDC" in rendered
    assert "PRICE_ASSET_ISSUER=rHuGNhqTG32mfmAvWA8hUyWRLV3tCSwKQt" in rendered
    assert "PRICE_ASSET_AMOUNT=2.50" in rendered
    assert "PAYMENT_ASSET=USDC:rHuGNhqTG32mfmAvWA8hUyWRLV3tCSwKQt" in rendered
    assert "ALLOWED_ISSUED_ASSETS=" in rendered


def test_demo_env_writes_xrp_variant_and_resets_issued_asset_fields(tmp_path: Path) -> None:
    base_path = tmp_path / ".env.quickstart"
    output_path = tmp_path / ".env.quickstart.xrp"
    base_path.write_text(
        BASE_ENV.replace("PRICE_DROPS=1000", "PRICE_DROPS=2500").replace(
            "ALLOWED_ISSUED_ASSETS=",
            "ALLOWED_ISSUED_ASSETS=RLUSD:rCustomRLUSDIssuer",
        ),
        encoding="utf-8",
    )

    exit_code = demo_env.main(
        [
            "--asset",
            "xrp",
            "--base",
            str(base_path),
            "--output",
            str(output_path),
        ]
    )

    rendered = output_path.read_text(encoding="utf-8")
    assert exit_code == 0
    assert "PRICE_DROPS=2500" in rendered
    assert "PRICE_ASSET_CODE=XRP" in rendered
    assert "PRICE_ASSET_ISSUER=" in rendered
    assert "PRICE_ASSET_AMOUNT=" in rendered
    assert "PAYMENT_ASSET=XRP:native" in rendered
    assert "ALLOWED_ISSUED_ASSETS=" in rendered
