from __future__ import annotations

from pathlib import Path

import devtools.demo_env as demo_env
from devtools.live_testnet_support import DemoWalletSet
from xrpl.wallet import Wallet


BASE_ENV = """# Generated by quickstart
XRPL_RPC_URL=https://resolved.testnet.rpc/
NETWORK_ID=xrpl:1
XRPL_NETWORK=xrpl:1
MY_DESTINATION_ADDRESS=rMerchant
FACILITATOR_BEARER_TOKEN=top-secret-token
XRPL_WALLET_SEED=sEdSuperSecretSeed
PRICE_DROPS=1000
PRICE_ASSET_CODE=XRP
PRICE_ASSET_ISSUER=
PRICE_ASSET_AMOUNT=
PAYMENT_ASSET=XRP:native
ALLOWED_ISSUED_ASSETS=
"""


def build_demo_wallet_set() -> DemoWalletSet:
    return DemoWalletSet(
        merchant_wallet=Wallet.create(),
        buyers={
            "xrp": Wallet.create(),
            "rlusd": Wallet.create(),
            "usdc": Wallet.create(),
        },
    )


def stub_demo_wallet_cache(monkeypatch, tmp_path: Path) -> DemoWalletSet:
    wallet_set = build_demo_wallet_set()
    monkeypatch.setattr(demo_env, "load_cached_demo_wallet_set", lambda _cache_path=None: wallet_set)
    monkeypatch.setattr(demo_env, "wallet_cache_path", lambda: tmp_path / "wallet-cache.json")
    return wallet_set


def test_demo_env_writes_rlusd_variant_with_extra_allowed_asset(
    monkeypatch,
    tmp_path: Path,
    capsys,
) -> None:
    wallet_set = stub_demo_wallet_cache(monkeypatch, tmp_path)
    base_path = tmp_path / ".env.quickstart"
    output_path = tmp_path / ".env.quickstart.rlusd"
    base_path.write_text(BASE_ENV, encoding="utf-8")
    monkeypatch.setattr(demo_env, "default_rlusd_issuer", lambda: "rCustomRLUSDIssuer")

    exit_code = demo_env.main(
        [
            "--asset",
            "rlusd",
            "--base",
            str(base_path),
            "--output",
            str(output_path),
        ]
    )
    captured = capsys.readouterr()

    rendered = output_path.read_text(encoding="utf-8")
    assert exit_code == 0
    assert "PRICE_ASSET_CODE=RLUSD" in rendered
    assert "PRICE_ASSET_ISSUER=rCustomRLUSDIssuer" in rendered
    assert "PRICE_ASSET_AMOUNT=1.25" in rendered
    assert "PAYMENT_ASSET=RLUSD:rCustomRLUSDIssuer" in rendered
    assert "ALLOWED_ISSUED_ASSETS=RLUSD:rCustomRLUSDIssuer" in rendered
    assert f"XRPL_WALLET_SEED={wallet_set.buyer_wallet('rlusd').seed}" in rendered
    assert wallet_set.buyer_wallet("xrp").seed not in rendered
    assert f"Buyer address: {wallet_set.buyer_wallet('rlusd').classic_address}" in captured.out
    assert "Buyer payment asset: RLUSD:rCustomRLUSDIssuer" in captured.out
    assert "Facilitator extra issued assets: RLUSD:rCustomRLUSDIssuer" in captured.out


def test_demo_env_writes_usdc_variant_without_extra_allowed_asset(
    monkeypatch,
    tmp_path: Path,
    capsys,
) -> None:
    wallet_set = stub_demo_wallet_cache(monkeypatch, tmp_path)
    base_path = tmp_path / ".env.quickstart"
    output_path = tmp_path / ".env.quickstart.usdc"
    base_path.write_text(BASE_ENV, encoding="utf-8")
    monkeypatch.setattr(demo_env, "default_usdc_issuer", lambda: "rHuGNhqTG32mfmAvWA8hUyWRLV3tCSwKQt")

    exit_code = demo_env.main(
        [
            "--asset",
            "usdc",
            "--base",
            str(base_path),
            "--output",
            str(output_path),
        ]
    )
    captured = capsys.readouterr()

    rendered = output_path.read_text(encoding="utf-8")
    assert exit_code == 0
    assert "PRICE_ASSET_CODE=USDC" in rendered
    assert "PRICE_ASSET_ISSUER=rHuGNhqTG32mfmAvWA8hUyWRLV3tCSwKQt" in rendered
    assert "PRICE_ASSET_AMOUNT=2.50" in rendered
    assert "PAYMENT_ASSET=USDC:rHuGNhqTG32mfmAvWA8hUyWRLV3tCSwKQt" in rendered
    assert "ALLOWED_ISSUED_ASSETS=" in rendered
    assert f"XRPL_WALLET_SEED={wallet_set.buyer_wallet('usdc').seed}" in rendered
    assert wallet_set.buyer_wallet("xrp").seed not in rendered
    assert f"Buyer address: {wallet_set.buyer_wallet('usdc').classic_address}" in captured.out


def test_demo_env_writes_xrp_variant_and_resets_issued_asset_fields(
    monkeypatch,
    tmp_path: Path,
) -> None:
    wallet_set = stub_demo_wallet_cache(monkeypatch, tmp_path)
    base_path = tmp_path / ".env.quickstart"
    output_path = tmp_path / ".env.quickstart.xrp"
    base_path.write_text(
        BASE_ENV.replace("PRICE_DROPS=1000", "PRICE_DROPS=2500").replace(
            "ALLOWED_ISSUED_ASSETS=",
            "ALLOWED_ISSUED_ASSETS=RLUSD:rCustomRLUSDIssuer",
        ),
        encoding="utf-8",
    )

    exit_code = demo_env.main(
        [
            "--asset",
            "xrp",
            "--base",
            str(base_path),
            "--output",
            str(output_path),
        ]
    )

    rendered = output_path.read_text(encoding="utf-8")
    assert exit_code == 0
    assert "PRICE_DROPS=2500" in rendered
    assert "PRICE_ASSET_CODE=XRP" in rendered
    assert "PRICE_ASSET_ISSUER=" in rendered
    assert "PRICE_ASSET_AMOUNT=" in rendered
    assert "PAYMENT_ASSET=XRP:native" in rendered
    assert "ALLOWED_ISSUED_ASSETS=" in rendered
    assert f"XRPL_WALLET_SEED={wallet_set.buyer_wallet('xrp').seed}" in rendered


def test_demo_env_variants_use_distinct_asset_specific_buyer_wallets(
    monkeypatch,
    tmp_path: Path,
) -> None:
    wallet_set = stub_demo_wallet_cache(monkeypatch, tmp_path)
    base_path = tmp_path / ".env.quickstart"
    base_path.write_text(BASE_ENV, encoding="utf-8")
    monkeypatch.setattr(demo_env, "default_rlusd_issuer", lambda: "rCustomRLUSDIssuer")
    monkeypatch.setattr(demo_env, "default_usdc_issuer", lambda: "rHuGNhqTG32mfmAvWA8hUyWRLV3tCSwKQt")

    for asset in ("xrp", "rlusd", "usdc"):
        exit_code = demo_env.main(
            [
                "--asset",
                asset,
                "--base",
                str(base_path),
                "--output",
                str(tmp_path / f".env.quickstart.{asset}"),
            ]
        )
        assert exit_code == 0

    rendered_by_asset = {
        asset: (tmp_path / f".env.quickstart.{asset}").read_text(encoding="utf-8")
        for asset in ("xrp", "rlusd", "usdc")
    }
    seeds = {
        asset: demo_env.get_env_value(
            demo_env.parse_env_lines(rendered_by_asset[asset]),
            "XRPL_WALLET_SEED",
        )
        for asset in rendered_by_asset
    }

    assert seeds == {
        "xrp": wallet_set.buyer_wallet("xrp").seed,
        "rlusd": wallet_set.buyer_wallet("rlusd").seed,
        "usdc": wallet_set.buyer_wallet("usdc").seed,
    }
    assert len(set(seeds.values())) == 3


def test_demo_env_requires_v2_demo_wallet_cache(monkeypatch, tmp_path: Path) -> None:
    base_path = tmp_path / ".env.quickstart"
    base_path.write_text(BASE_ENV, encoding="utf-8")
    monkeypatch.setattr(demo_env, "load_cached_demo_wallet_set", lambda _cache_path=None: None)
    monkeypatch.setattr(demo_env, "wallet_cache_path", lambda: tmp_path / "wallet-cache.json")

    try:
        demo_env.main(["--asset", "rlusd", "--base", str(base_path)])
    except RuntimeError as exc:
        assert "Rerun `python -m devtools.quickstart` first." in str(exc)
    else:
        raise AssertionError("Expected demo_env.main to fail when the wallet cache is missing")
