from __future__ import annotations

import argparse
import secrets
from pathlib import Path
from typing import Sequence

from xrpl.clients import JsonRpcClient
from xrpl.wallet import Wallet

from devtools.live_testnet_support import TESTNET_RPC_URL, get_live_wallet_pair, wallet_cache_path

DEFAULT_OUTPUT_PATH = Path(".env.quickstart")
DEFAULT_PRICE_DROPS = 1000


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a reusable XRPL Testnet quickstart environment file for the "
            "facilitator, merchant, and buyer demo stack."
        ),
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT_PATH),
        help="Path to the generated Docker Compose env file",
    )
    parser.add_argument(
        "--price-drops",
        type=int,
        default=DEFAULT_PRICE_DROPS,
        help="XRP price for the demo merchant route, in drops",
    )
    parser.add_argument(
        "--facilitator-token",
        default=None,
        help="Optional facilitator bearer token to write instead of generating one",
    )
    return parser


def render_quickstart_env(
    *,
    merchant_wallet: Wallet,
    buyer_wallet: Wallet,
    facilitator_token: str,
    price_drops: int,
) -> str:
    buyer_seed = buyer_wallet.seed
    if buyer_seed is None:
        raise RuntimeError("Buyer wallet is missing a seed")

    lines = [
        "# Generated by `python -m devtools.quickstart`.",
        "# Contains secrets for local XRPL Testnet demos. Do not commit this file.",
        "GATEWAY_AUTH_MODE=single_token",
        f"XRPL_RPC_URL={TESTNET_RPC_URL}",
        "NETWORK_ID=xrpl:1",
        "XRPL_NETWORK=xrpl:1",
        "SETTLEMENT_MODE=validated",
        f"MY_DESTINATION_ADDRESS={merchant_wallet.classic_address}",
        f"FACILITATOR_BEARER_TOKEN={facilitator_token}",
        f"XRPL_WALLET_SEED={buyer_seed}",
        f"PRICE_DROPS={price_drops}",
        "PRICE_ASSET_CODE=XRP",
        "PRICE_ASSET_ISSUER=",
        "PRICE_ASSET_AMOUNT=",
        "PAYMENT_ASSET=XRP:native",
        "",
        "# To demo RLUSD, set PRICE_ASSET_CODE/ISSUER/AMOUNT and PAYMENT_ASSET accordingly.",
        "# To demo USDC, set PRICE_ASSET_CODE/ISSUER/AMOUNT and PAYMENT_ASSET accordingly.",
        "",
    ]
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    client = JsonRpcClient(TESTNET_RPC_URL)
    wallets = get_live_wallet_pair(client)
    merchant_wallet = wallets.wallet_a
    buyer_wallet = wallets.wallet_b

    facilitator_token = args.facilitator_token or secrets.token_urlsafe(24)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_quickstart_env(
            merchant_wallet=merchant_wallet,
            buyer_wallet=buyer_wallet,
            facilitator_token=facilitator_token,
            price_drops=args.price_drops,
        ),
        encoding="utf-8",
    )

    buyer_seed = buyer_wallet.seed
    if buyer_seed is None:
        raise RuntimeError("Buyer wallet is missing a seed")

    print(f"Wrote {output_path}")
    print(f"Merchant address: {merchant_wallet.classic_address}")
    print(f"Buyer address: {buyer_wallet.classic_address}")
    print(f"Buyer seed: {buyer_seed}")
    print(f"Facilitator bearer token: {facilitator_token}")
    print(f"Wallet cache: {wallet_cache_path()}")
    print("Next steps:")
    print(f"  docker compose --env-file {output_path} up --build")
    print(f"  docker compose --env-file {output_path} run --rm --profile demo buyer")
    print("Asset follow-ups:")
    print("  python -m devtools.rlusd_topup")
    print("  python -m devtools.usdc_topup")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
